#!/bin/zsh
#PBS -lselect=18:ncpus=28:mpiprocs=1:model=bro_ele
#PBS -lwalltime=100:00:00
#PBS -q long
#PBS -j oe


# Make sure that you are requeting the correct number of cores for your machine!
# https://www.nas.nasa.gov/hecc/support/kb/pbs-resource-request-examples_188.html - Aitken
# https://www.nas.nasa.gov/hecc/resources/athena.html - Athena
# https://hec.nasa.gov/user/policies/sbus.html - SBU info with cores


source $HOME/.profile
source $HOME/.zshrc

loadSedona

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=28
export OMP_THREAD_LIMIT=28
export OMP_PLACES=cores
export OMP_PROC_BIND=spread,close
export OMP_MAX_ACTIVE_LEVELS=2

# Run the python grid
python runGridHECC.py "$TARGET_DIR"
